Store.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Store.Data.Models;
using Store.Repo;
using Store.Data.ViewModels;

namespace Store.Web.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;
        private readonly ApplicationContext _context;
        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationContext context, UserManager<User> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            _context = context;
        }


        [HttpGet]
        public IActionResult Index()
        {
            ApplicationRole model = new ApplicationRole();
            var roles = _context.Roles;
            ViewBag.Roles = roles;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEditApplicationRole(string id, ApplicationRole model)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(id);
                IdentityRole applicationRole = isExist ? await _context.Roles.FindAsync(id) :
               new IdentityRole
               {
               };
                applicationRole.Name = model.Name;

                IdentityResult roleRuslt = isExist ? await roleManager.UpdateAsync(applicationRole)
                                                    : await roleManager.CreateAsync(applicationRole);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(string id)
        {
            bool isExist = !String.IsNullOrEmpty(id);
            if (isExist)
            {
                IdentityRole applicationRole = await _context.Roles.FindAsync(id);
                IdentityResult roleRuslt = await roleManager.DeleteAsync(applicationRole);
            }
            return RedirectToAction("Index");
        }




        public async Task<IActionResult> Premission(string id)
        {
            EditUserViewModel model = new EditUserViewModel();
            model.ApplicationRoles = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            ViewBag.ApplicationRoleId = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            if (!String.IsNullOrEmpty(id))
            {
                User user = await userManager.FindByIdAsync(id);
                var userrole = await userManager.GetRolesAsync(user);
                model.UserRoles = (List<string>)userrole;
                model.UserName = user.UserName;
                if (user != null)
                {
                    model.UserId = id;
                    //  model.ApplicationRoleId = roleManager.Roles.Single(r => r.Name == userManager.GetRolesAsync(user).Result.Single()).Id;
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignRoleToUser(EditUserViewModel model)
        {
            if (model.ApplicationRoleId != null)
            {
                var user = await userManager.FindByIdAsync(model.UserId);
                var rolename = roleManager.Roles.Where(c => c.Id == model.ApplicationRoleId).SingleOrDefault();
                if (!await userManager.IsInRoleAsync(user, model.ApplicationRoleId))
                {
                    await userManager.AddToRoleAsync(user, rolename.Name);
                }
            }
            return RedirectToAction("Premission", new { id = model.UserId });
        }
        public async Task<IActionResult> DeleteRoleToUser(string item, string UserId)
        {

            if (item != null)
            {
                var user = await userManager.FindByIdAsync(UserId);
                var rolename = roleManager.Roles.Where(c => c.Name.Contains(item)).SingleOrDefault();
                if (rolename != null)
                {
                    await userManager.RemoveFromRoleAsync(user, rolename.Name);
                }
            }
            return RedirectToAction("Premission", new { id = UserId });
        }

    }
}

Store.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Store.Data;
using Store.Data.Models;
using Store.Data.ViewModels;
using Store.Service;


namespace Store.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IHostingEnvironment _environment;
        //private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public UserController(IUserService userService, IHostingEnvironment environment, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.userService = userService;
            _environment = environment;
          
            _userManager = userManager;
            _signInManager = signInManager;
        }


        #region Index 
        public async Task<IActionResult> Index(int? page, string SearchString)
        {
            var users = userService.GetUsers();
            if (SearchString != null)
            {
                users = users.Where(x => x.UserName.Contains(SearchString));
            }
            if (users.Count() <= 10) { page = 1; }
            int pageSize = 10;
            return View(await PaginatedList<User>.CreateAsync(users, page ?? 1, pageSize));
        }
        //#endregion

        //#region Add

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                userViewModel.Password = "Abc123@@";
                var user = new User { UserName = userViewModel.Email, Email = userViewModel.Email ,FirstName=userViewModel.FirstName  , LastName = userViewModel.LastName};
                var result = await _userManager.CreateAsync(user, userViewModel.Password);
                if (result.Succeeded)
                {
                    // Add a user to the default role, or any role you prefer here
                   // await _userManager.AddToRoleAsync(user, "Doctor");
                    return RedirectToAction("Index", "User");
                }
            }
            return View(userViewModel);
        }
        #endregion


        public async Task<IActionResult> Delete(string id)
        {
            bool isExist = !String.IsNullOrEmpty(id);
            if (isExist)
            {

                User usermodel = await _userManager.FindByIdAsync(id);
                if (usermodel!=null) {

                    await _userManager.DeleteAsync(usermodel);
                }
            }
            return RedirectToAction("Index");
        }
    }
    }

Store.Web/Views/User/Add.cshtml
@model Store.Data.ViewModels.UserViewModel
@{
    ViewData["Title"] = "Add";
}
<br />
<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li><a href="index.html">Home</a></li>
                <li class="active"><a href="wishlist.html">Add User</a></li>
            </ul>
        </div>
    </div>

</div>

<br />

<div class="container">
    <div class="coupon-accordion">
        <!-- ACCORDION START -->
        <h3>Add User <span id="showlogin"></span></h3>
        <div id="checkout-login" class="coupon-content" style="display: block;">
            <div class="coupon-info">
                <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <br />
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                    </div>
                    <input type="submit" value="Add" class="return-customer-btn">
                </form>
            </div>
        </div>
    </div>
</div>

Store.Web/Views/User/Index.cshtml
@model IEnumerable<Store.Data.Models.User>


<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li><a href="index.html">Home</a></li>
                <li class="active"><a href="wishlist.html">Users</a></li>
            </ul>
        </div>
    </div>

</div>

<div class="cart-main-area wish-list ptb-45">

    <div class="container">

        <a asp-action="Add" class="btn btn-info">
             Add User
        </a>
        <div class="coupon-accordion">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <br />
                    <br />
                    <div class="table-content table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="product-remove">First Name</th>
                                    <th class="product-thumbnail">Last Name</th>
                                    <th class="product-name">Email</th>
                                    <th class="product-price">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                    <td>
                                        @*<a id="editUserModal" data-toggle="modal" asp-action="EditUser" asp-route-id="@item.Id" data-target="#modal-action-user"
                                           class="btn btn-info">
                                            <i class="glyphicon glyphicon-pencil"></i>  Edit
                                        </a>*@
                                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
                                            <i class="glyphicon glyphicon-trash"></i>  Delete
                                        </a>
                                        <a asp-action="Premission" asp-controller="Role" asp-route-id="@item.Id" class="btn btn-warning">
                                            <i class="glyphicon glyphicon-edit"></i>  Premission
                                        </a>
                                    </td>
                                </tr>
                        }
                            </tbody>

                        </table>
                    </div>



                </div>
            </div>
        </div>
    </div>
</div>