Store.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Store.Data.ViewModels;
using Store.Service.IServices;
using Store.Service.Services;

namespace Store.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICatigoryService Service ;

        public CategoriesController(ICatigoryService _Service)
        {
            this.Service = _Service;
        }

        public IActionResult Index()
        {        
            ViewBag.Catogeries  = Service.getCatigories();
            return View();
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CatigoryViewModel data)
        {
            if (ModelState.IsValid)
            {
                bool success = Service.Add(data);
                if (success)
                {
                    return RedirectToAction("Index");
                }
            }
           
            return RedirectToAction("Index");
        }
       
        public IActionResult Delete(int ID)
        {
            if (ID>0)
            {
                var selected =  Service.Delete(ID);
            }
            return RedirectToAction("Index");
        }

        
        public IActionResult DeleteCatigory(int Id)
        {
            bool success = Service.Delete(Id);
            if (success)
            {
                return RedirectToAction("Index");
            }
            return View("Error");
        }
    }
}

Store.Web/Views/Categories/Index.cshtml
@model Store.Data.ViewModels.CatigoryViewModel
@{
    ViewData["Title"] = "Catigories";
}

<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li><a href="index.html">Home</a></li>
                <li class="active"><a href="wishlist.html">Categories</a></li>
            </ul>
        </div>
    </div>

</div>



<div class="cart-main-area wish-list ptb-45">

    <div class="container">
        <div class="coupon-accordion">
            <!-- ACCORDION START -->
            <h3>Add Categories <span id="showlogin"></span></h3>
            <div id="checkout-login" class="coupon-content" style="display: block;">
                <div class="coupon-info">
                   
                    <form id="myForm" asp-action="Add" asp-controller="Categories" method="post">
                        <div class="modal-body">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="checkout-form-list mb-sm-30">
                                        <label asp-for="EnName" class="control-label">English Name</label>
                                        <input asp-for="EnName" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="checkout-form-list mb-30">
                                        <label asp-for="ArName" class="control-label">Arabic Name</label>
                                        <input asp-for="ArName" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" id="btnSubmit" class="btn btn-info"> Add Catogry </button>
                        </div>
                    </form>

                </div>



            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <br />
                    <br />
                    <div class="table-content table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="product-remove">Id</th>
                                    <th class="product-thumbnail">English Name</th>
                                    <th class="product-name">Arabic Name</th>
                                    <th class="product-price">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.Catogeries)
                                {
                                    <tr>
                                        <td>@item.ID</td>
                                        <td>@item.EnName</td>
                                        <td>@item.ArName</td>

                                        <td>
                                            <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                                                <i class="glyphicon glyphicon-trash"></i>  Delete
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>



                </div>
           </div>


                
            </div>
        </div>
    </div>